### Site info:
title: Florian Kuhn
tagline: ""
author: Florian Kuhn
email: kuhn@ids-mannheim.de
description: "This is my personal page on natural language processing, machine learning and programming" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "research, python, nlp, personal page"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fkuhn.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: zeichenkette
github_username:  fkuhn
favicon:     "/images/favicon.ico"
aboutme: "" # these are shown on aboutme-sidebar.
aboutme_photo: http://i.imgur.com/IM7pAIF.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: github.com/fkuhn
      href: http://fkuhn.github.io
      title: My personal github page
    - name: Zeichenkette
      href: http://zeichenkette.de/
      title: My poetry related blog (german)


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
